version: '3.9'
services:
  umami:
    image: ghcr.io/umami-software/umami:postgresql-latest
    depends_on:
      - umami-db
    env_file:
      - config/env/umami.env
    ports:
      - "3000:3000"
    restart: unless-stopped
  umami-db:
    image: postgres:16-alpine
    env_file:
      - config/env/umami.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - umami_db:/var/lib/postgresql/data
    restart: unless-stopped
volumes:
  umami_db:
