services:
  payments:
    image: ghcr.io/saltdocker/payments:v2
    restart: unless-stopped
    environment:
      APP_ENV: dev
    ports:
    - 8080:8080
    labels:
    - traefik.enable=true
    - traefik.http.routers.payments.rule=Host(`pay.local.salt`)
    - traefik.http.routers.payments.entrypoints=websecure
    - traefik.http.services.payments.loadbalancer.server.port=8080
