services:
  plausible:
    image: plausible/analytics:latest
    depends_on:
      - plausible-db
      - plausible-events-db
    env_file:
      - config/env/plausible.env
    ports:
      - "8000:8000"
    restart: unless-stopped
  plausible-db:
    image: postgres:16-alpine
    env_file:
      - config/env/plausible.env
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - plausible_db:/var/lib/postgresql/data
    restart: unless-stopped
  plausible-events-db:
    image: clickhouse/clickhouse-server:24.8
    env_file:
      - config/env/plausible.env
    volumes:
      - plausible_events_db:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    restart: unless-stopped
volumes:
  plausible_db:
  plausible_events_db:
