services:
  traefik:
    image: traefik:v3.0
    env_file:
      - config/env/gateway.env
    command:
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--providers.file.directory=/etc/traefik/dynamic"
      - "--providers.docker=true"
      - "--providers.file.watch=true"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.email=${TRAEFIK_ACME_EMAIL:-ssl@tschenfeng.com}"
      - "--certificatesresolvers.le.acme.storage=/etc/traefik/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./../traefik/dynamic:/etc/traefik/dynamic"
      - "./../traefik/certs:/etc/traefik/certs"
      - "./../traefik/acme:/etc/traefik"
    networks:
      - saltdocker_proxy
networks:
  saltdocker_proxy:
    external: true
