services:
  mattermost:
    image: mattermost/mattermost-team-edition:latest
    depends_on:
      - mattermost-db
      - mattermost-minio
    env_file:
      - config/env/mattermost.env
    environment:
      - MM_SQLSETTINGS_DATASOURCE=postgres://\${POSTGRES_USER}:\${POSTGRES_PASSWORD}@mattermost-db:5432/\${POSTGRES_DB}?sslmode=disable&connect_timeout=10
      - MM_FILESETTINGS_AMAZONS3ENDPOINT=mattermost-minio:9000
      - MM_SERVICESETTINGS_SITEURL=https://mm.local.salt
    ports:
      - "8065:8065"
    volumes:
      - mattermost_data:/mattermost/data
    restart: unless-stopped
  mattermost-db:
    image: postgres:15
    env_file:
      - config/env/mattermost.env
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - mattermost_db:/var/lib/postgresql/data
    restart: unless-stopped
  mattermost-minio:
    image: minio/minio:RELEASE.2024-01-05T22-17-24Z
    command: server /data
    env_file:
      - config/env/mattermost.env
    volumes:
      - mattermost_minio:/data
    ports:
      - "9001:9000"
    restart: unless-stopped
volumes:
  mattermost_data:
  mattermost_db:
  mattermost_minio:
